services:
  - type: web
    name: technews-backend
    env: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false

  - type: web
    name: technews-frontend
    env: static
    region: ohio
    plan: free
    buildCommand: npm install && CI=false npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_NEWS_API_KEY
        sync: false
      - key: REACT_APP_API_URL
        value: https://technews-backend.onrender.com 