services:
  - type: web
    name: technews-updates
    env: node
    region: ohio
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build && cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://technews-updates.onrender.com
      - key: NEWS_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false
